title: Tent App Post
type: object
properties:
  name:
    description: The short display name for the app.
    type: string
    required: true
  description:
    description: The short display description of the app.
    type: string
    required: true
  url:
    description: The URL for the home page of the app.
    type: string
    format: uri
    required: true
  icon:
    description: The URL to the icon for the app.
    type: string
    format: uri
  redirect_uri:
    description: The exact (including parameters) uri that will be used as OAuth `redirect_uri`.
    type: string
    format: uri
  scopes:
    description:
      All of the scopes that the application will use, and the reason why each is required.
    required: true
    type: object
    patternProperties:
      .+:
        type: string
