title: App
type: object
additionalProperties: false
properties:
  name:
    description: The name of the app.
    type: string
    required: true
  description:
    description: The description of the app.
    type: string
    required: false
  url:
    description: The URL for the website of the app.
    type: string
    format: uri
    required: true
  redirect_uri:
    description: The URL that will be used as OAuth `redirect_uri`.
    type: string
    format: uri
    required: true
  notification_url:
    description: The URL where post notifications will be delivered.
    type: string
    format: uri
    required: false
  notification_types:
    description: The list of type URIs that the app wants to receive notifications about.
    type: array
    required: false
    items:
      type: string
      format: https://tent.io/formats/type-selector
  types:
    description: The list of type URIs that the app wants access to.
    type: object
    required: false
    additionalProperties: false
    properties:
      read:
        description: The list of type URIs that the app wants to read.
        type: array
        required: false
        app_required: false
        items:
          type: string
          format: uri
          format: https://tent.io/formats/type-selector
      write:
        description: The list of type URIs that the app wants to read and modify.
        type: array
        required: false
        items:
          type: string
          format: https://tent.io/formats/type-selector
  scopes:
    description: The list of requested scopes.
    required: true
    type: array
    required: false
    items:
      type: string

